version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db_for_wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress_db
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network_wordpress


  wordpress:
    depends_on:
      - db
    image: wordpress:5.6.1-fpm-alpine
    container_name: wordpress_project
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress_db
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php-conf/php:/usr/local/etc/php
    networks:
      - app-network_wordpress
    
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.19.6-alpine
    container_name: webserver_for_wordpress
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress/html:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - app-network_wordpress


  certbot:
   depends_on:
      - webserver
   image: certbot/certbot
   container_name: certbot_for_arhproject.h1n.ru
   volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./wordpress/html:/var/www/html
   command: certonly --webroot --webroot-path=/var/www/html --email vyacheslav25@gmail.com --agree-tos --no-eff-email --force-renewal -d arhproject.h1n.ru -d www.arhproject.h1n.ru

volumes:
#    certbot-etc:
#   wordpress:
   dbdata:

networks:
   app-network_wordpress:
             driver: bridge
